// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbi_D-zLEZqP7ccXSPh8tocd6Ly29D2K8',
    appId: '1:1077599017535:web:065c84e711fa823461368a',
    messagingSenderId: '1077599017535',
    projectId: 'women-safety-sos-b537a',
    authDomain: 'women-safety-sos-b537a.firebaseapp.com',
    storageBucket: 'women-safety-sos-b537a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrZKM_wGtnpRAUDAjix443dI0Qv0F_znQ',
    appId: '1:1077599017535:android:bd1c308f4963ae8661368a',
    messagingSenderId: '1077599017535',
    projectId: 'women-safety-sos-b537a',
    storageBucket: 'women-safety-sos-b537a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRBVO5BRqM2eOAiLfB4MN2wiAWO_tRmxo',
    appId: '1:1077599017535:ios:cdafeeea7c6df01961368a',
    messagingSenderId: '1077599017535',
    projectId: 'women-safety-sos-b537a',
    storageBucket: 'women-safety-sos-b537a.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRBVO5BRqM2eOAiLfB4MN2wiAWO_tRmxo',
    appId: '1:1077599017535:ios:cdafeeea7c6df01961368a',
    messagingSenderId: '1077599017535',
    projectId: 'women-safety-sos-b537a',
    storageBucket: 'women-safety-sos-b537a.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbi_D-zLEZqP7ccXSPh8tocd6Ly29D2K8',
    appId: '1:1077599017535:web:a144de00f784795b61368a',
    messagingSenderId: '1077599017535',
    projectId: 'women-safety-sos-b537a',
    authDomain: 'women-safety-sos-b537a.firebaseapp.com',
    storageBucket: 'women-safety-sos-b537a.firebasestorage.app',
  );
}
